version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app_net

  service1:
    build: ./service_1
    expose:
      - "8001"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      retries: 3

  service2:
    build: ./service_2
    expose:
      - "8002"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      retries: 3

networks:
  app_net:
    driver: bridge
